#!/usr/bin/env node
// gen-version.js — single source of truth: package.json "version".
// Generates:
//   src/pkjs/version.js        -> module.exports = '1.0.1'  (JS cache versioning)
//   src/c/version.auto.h       -> #define PG_APP_VERSION "1.0.1" (C debug line)
// Run automatically via wscript pre-step (or manually: node tools/gen-version.js)
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = String(pkg.version || '0.0.0');

const jsOut = path.join(root, 'src/pkjs/version.js');
fs.writeFileSync(jsOut, "// AUTO-GENERATED by tools/gen-version.js — do not edit.\n" +
  "module.exports = '" + version + "';\n");

const cOut = path.join(root, 'src/c/version.auto.h');
fs.writeFileSync(cOut, "// AUTO-GENERATED by tools/gen-version.js — do not edit.\n" +
  "#define PG_APP_VERSION \"" + version + "\"\n");

console.log('version.js + version.auto.h generated: ' + version);
