#!/usr/bin/env node
// gen-version.js — single source of truth: package.json "version".
// Generates:
//   src/pkjs/version.js        -> module.exports = '1.0.1'  (JS cache versioning)
//   src/c/version.auto.h       -> #define PG_APP_VERSION "1.0.1" (C debug line)
// Run automatically via wscript pre-step (or manually: node tools/gen-version.js)
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = String(pkg.version || '0.0.0');

const jsOut = path.join(root, 'src/pkjs/version.js');
fs.writeFileSync(jsOut, "// AUTO-GENERATED by tools/gen-version.js — do not edit.\n" +
  "module.exports = '" + version + "';\n");

const cOut = path.join(root, 'src/c/version.auto.h');
fs.writeFileSync(cOut, "// AUTO-GENERATED by tools/gen-version.js — do not edit.\n" +
  "#define PG_APP_VERSION \"" + version + "\"\n");

// Guard against the stale build/js/message_keys.json trap: the waf
// message_key_json task does not reliably re-run when package.json
// messageKeys grows, so webpack can generate a message_keys module
// missing newly added keys (cost us: ThreadList never reached the
// watch). Deleting the file forces regeneration on the next build.
const keysJson = path.join(root, 'build/js/message_keys.json');
if (fs.existsSync(keysJson)) {
  try {
    const pkgKeys = (pkg.pebble && pkg.pebble.messageKeys) || [];
    const builtKeys = JSON.parse(fs.readFileSync(keysJson, 'utf8'));
    const missing = pkgKeys.filter(function(k) {
      return !(k in builtKeys);
    });
    if (missing.length > 0) {
      fs.unlinkSync(keysJson);
      console.log('stale message_keys.json removed (missing: ' + missing.join(', ') + ')');
    }
  } catch (e) {
    // Unreadable JSON — delete so the build regenerates it.
    try { fs.unlinkSync(keysJson); } catch (e2) {}
    console.log('stale/unreadable message_keys.json removed');
  }
}

console.log('version.js + version.auto.h generated: ' + version);
